#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Radar en Railway (producción). En Git Bash, desde la raíz de un checkout del
# repo, con la CLI de Railway logueada:
#
#   bash scripts/radar_produccion_railway.sh
#
# A diferencia de staging: proyecto de Railway propio, WAHA sin dominio público
# (Radar y WAHA se hablan por la red privada), dominio propio, imagen de WAHA
# con versión fija y backups de las bases y del volumen de claves. Despliega la
# rama develop: el PR de Radar tiene que estar mergeado.
#
# Guarda lo que generás o pegás en ~/.radar-produccion.env (fuera del repo).

TOTAL_STAGES=13
umask 077
ENV_FILE="${RADAR_WIZARD_ENV:-$HOME/.radar-produccion.env}"
REPO_SLUG="maoscherov/WhatsappBoty"
RAMA="develop"

_o_default() { local v; v=$(_existing "$1" || true); printf '%s' "${v:-$2}"; }

_secreto() {
  local key="$1" largo="$2" valor
  valor=$(_existing "$key" || true)
  if [[ -z "$valor" ]]; then
    valor=$(python -c "import secrets; print(secrets.token_urlsafe($largo))")
    write_env "$key" "$valor"
  else
    printf '  %s✓ ya estaba%s %s\n' "$GREEN" "$RESET" "$key"
  fi
  printf -v "$key" '%s' "$valor"
}

banner "Radar en Railway (producción)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Antes de empezar"
say "Este asistente monta Radar de producción en un proyecto de Railway propio, desde la rama $RAMA."
say "Lo que generes o pegues queda en $ENV_FILE (solo lo puede leer tu usuario)."
if [[ ! -f app/radar/app.py || ! -f railway.json ]]; then
  warn "Corrélo desde la raíz de un checkout del repo que tenga Radar (app/radar)."
  exit 1
fi
if [[ "$ENV_FILE" == /root/* ]]; then
  warn "Estás en WSL. Corrélo en Git Bash: \"C:\\Program Files\\Git\\bin\\bash.exe\" scripts/radar_produccion_railway.sh"
  exit 1
fi
for cmd in railway curl python git openssl sha512sum; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    warn "Falta $cmd en el PATH."
    exit 1
  fi
done
git fetch -q origin "$RAMA" || true
if ! git cat-file -e "origin/$RAMA:app/radar/app.py" 2>/dev/null; then
  warn "origin/$RAMA todavía no tiene Radar: mergeá primero el PR de feature/radar-tramo2."
  exit 1
fi
if ! railway whoami >/dev/null 2>&1; then
  step "Iniciá sesión en Railway (se abre el navegador):"
  railway login
fi
say "✓ Todo en orden: origin/$RAMA ya tiene Radar."
pause "Enter para seguir"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Proyecto de Railway propio"
say "Radar de producción va en un proyecto aparte: no comparte red, bases ni WAHA con el bot ni con tu línea personal."
if confirm "¿Creo un proyecto nuevo llamado «Radar»? (No = elegir uno que ya exista)"; then
  railway init --name Radar
else
  step "Elegí el proyecto de Radar con las flechas y Enter."
  railway link || warn "railway link no terminó bien; si ya vinculaste la carpeta, seguí."
fi
railway status || true
pause "Enter para seguir"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Las dos bases de Postgres, con backups"
railway open >/dev/null 2>&1 || warn "No se pudo abrir el proyecto: abrilo en railway.com."
step "En el proyecto: «+ Create» → Database → PostgreSQL. Repetilo: tienen que ser dos."
step "Renombralas (clic en el servicio → Settings → nombre del servicio):"
say "      RadarResultados   y   RadarFuente"
step "En cada una: pestaña Backups → activá los backups programados."
pause "Enter cuando estén las dos creadas, renombradas y con backups"
ask RESULTADOS_SVC "Nombre de la base de resultados [$(_o_default RESULTADOS_SVC RadarResultados)]:"
RESULTADOS_SVC=${RESULTADOS_SVC:-RadarResultados}
ask FUENTE_SVC "Nombre de la base de fuente [$(_o_default FUENTE_SVC RadarFuente)]:"
FUENTE_SVC=${FUENTE_SVC:-RadarFuente}
for svc in "$RESULTADOS_SVC" "$FUENTE_SVC"; do
  if railway variables --service "$svc" --kv >/dev/null 2>&1; then
    say "✓ Encontré $svc."
  else
    warn "No encontré el servicio $svc en el proyecto vinculado. Revisá el nombre antes de seguir."
  fi
done
write_env RESULTADOS_SVC "$RESULTADOS_SVC"
write_env FUENTE_SVC "$FUENTE_SVC"
pause "Enter para seguir"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "WAHA de producción"
say "Un WAHA nuevo, solo para las líneas de los clientes: sin dominio público y con versión fija."
ask WAHA_TAG "Imagen (tag de devlikeapro/waha) [$(_o_default WAHA_TAG gows-2026.9.2)]:"
WAHA_TAG=${WAHA_TAG:-gows-2026.9.2}
ask WAHA_SVC "Nombre del servicio [$(_o_default WAHA_SVC waha-radar)]:"
WAHA_SVC=${WAHA_SVC:-waha-radar}
write_env WAHA_TAG "$WAHA_TAG"
write_env WAHA_SVC "$WAHA_SVC"
WAHA_ADMIN_KEY=$(_existing WAHA_ADMIN_KEY || true)
if [[ -z "$WAHA_ADMIN_KEY" ]]; then
  WAHA_ADMIN_KEY=$(openssl rand -hex 32)
  write_env WAHA_ADMIN_KEY "$WAHA_ADMIN_KEY"
fi
WAHA_KEY_HASH=$(printf '%s' "$WAHA_ADMIN_KEY" | sha512sum | cut -d' ' -f1)
_secreto WAHA_PANEL_PASSWORD 24
note "La clave admin en claro queda en $ENV_FILE: copiala también a tu gestor de contraseñas."
waha_vars=(
  "WHATSAPP_DEFAULT_ENGINE=GOWS"
  "WHATSAPP_API_PORT=3000"
  "PORT=3000"
  "TZ=America/Argentina/Buenos_Aires"
  "WAHA_API_KEY=sha512:${WAHA_KEY_HASH}"
  "WAHA_DASHBOARD_ENABLED=false"
  "WAHA_DASHBOARD_USERNAME=radar"
  "WAHA_DASHBOARD_PASSWORD=${WAHA_PANEL_PASSWORD}"
  "WHATSAPP_SWAGGER_ENABLED=false"
  "WHATSAPP_SWAGGER_USERNAME=radar"
  "WHATSAPP_SWAGGER_PASSWORD=${WAHA_PANEL_PASSWORD}"
  "WAHA_APPS_ENABLED=false"
  "WAHA_PRINT_QR=False"
  "WAHA_WORKER_ID=radar-prod-1"
  "WAHA_WORKER_RESTART_SESSIONS=True"
  "WHATSAPP_RESTART_ALL_SESSIONS=False"
  "WAHA_LOCAL_STORE_BASE_DIR=/app/.sessions"
  "WAHA_NAMESPACE=all"
  "WAHA_PRESENCE_AUTO_ONLINE=False"
  "WAHA_SESSION_CONFIG_IGNORE_STATUS=true"
  "WAHA_SESSION_CONFIG_IGNORE_GROUPS=true"
  "WAHA_SESSION_CONFIG_IGNORE_CHANNELS=true"
  "WAHA_SESSION_CONFIG_IGNORE_BROADCAST=true"
  "WAHA_EVENTS_DOWNLOAD_MEDIA=false"
  "WAHA_API_DOWNLOAD_MEDIA=false"
  "WAHA_MEDIA_STORAGE=LOCAL"
  "WHATSAPP_FILES_LIFETIME=180"
  "WAHA_LOG_LEVEL=info"
  "WAHA_LOG_FORMAT=JSON"
  "WAHA_HTTP_LOG_LEVEL=info"
  "WAHA_GOWS_DEVICE_REQUIRE_FULL_SYNC=false"
  "WAHA_GOWS_DEVICE_HISTORY_SYNC_FULL_SYNC_DAYS_LIMIT=90"
  "WAHA_GOWS_DEVICE_HISTORY_SYNC_RECENT_SYNC_DAYS_LIMIT=90"
  "WAHA_GOWS_DEVICE_HISTORY_SYNC_INITIAL_SYNC_MAX_MESSAGES_PER_CHAT=5000"
)
note "Historial: 90 días y 5000 mensajes por chat, como el staging, hasta que el spike fije los valores."
if railway variables --service "$WAHA_SVC" --kv >/dev/null 2>&1; then
  say "✓ El servicio $WAHA_SVC ya existe."
  if confirm "¿Le vuelvo a cargar las variables (sin cambiar la clave guardada)?"; then
    args=(); for v in "${waha_vars[@]}"; do args+=(--set "$v"); done
    railway variables --service "$WAHA_SVC" "${args[@]}" >/dev/null && say "✓ Variables cargadas."
  fi
elif confirm "¿Creo el servicio $WAHA_SVC con devlikeapro/waha:$WAHA_TAG?"; then
  args=(); for v in "${waha_vars[@]}"; do args+=(--variables "$v"); done
  railway add --service "$WAHA_SVC" --image "devlikeapro/waha:$WAHA_TAG" "${args[@]}" >/dev/null \
    && say "✓ Servicio creado." || { warn "railway add falló."; exit 1; }
else
  SKIPPED+=("crear el servicio de WAHA (paso 4)")
fi
railway service "$WAHA_SVC" >/dev/null 2>&1 || true
volumenes=$(railway volume list 2>/dev/null || true)
if grep -q "/app/.sessions" <<<"$volumenes"; then
  say "✓ Ya hay un volumen en /app/.sessions."
elif confirm "¿Le creo el volumen en /app/.sessions?"; then
  railway volume add --mount-path /app/.sessions
fi
warn "A este servicio NO le generes dominio y NO le actives backups del volumen (es la copia de los chats de los clientes)."
pause "Enter para seguir"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "El servicio de Radar"
step "En el proyecto: «+ Create» → GitHub Repo → $REPO_SLUG."
step "Renombralo a «radar» (Settings → nombre del servicio)."
step "Settings → Source → Branch: $RAMA."
note "Si arranca un deploy antes de que cargues las variables y falla, es normal."
pause "Enter cuando el servicio exista y apunte a $RAMA"
ask RADAR_SVC "Nombre del servicio de Radar [$(_o_default RADAR_SVC radar)]:"
RADAR_SVC=${RADAR_SVC:-radar}
write_env RADAR_SVC "$RADAR_SVC"
railway service "$RADAR_SVC" || warn "No pude vincular el servicio $RADAR_SVC; revisá el nombre."
pause "Enter para seguir"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Volumen de claves, con backups"
say "Acá viven la clave de cada cliente y la clave admin de WAHA. Si se pierde el volumen, no hay vuelta atrás."
volumenes=$(railway volume list 2>/dev/null || true)
if grep -q " /data" <<<"$volumenes" || grep -q "^/data" <<<"$volumenes"; then
  say "✓ Ya hay un volumen montado en /data."
elif confirm "¿Creo el volumen en /data para $RADAR_SVC?"; then
  railway volume add --mount-path /data
fi
step "En el volumen de $RADAR_SVC: pestaña Backups → activá los backups programados."
pause "Enter cuando estén activos"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Dominio propio"
ask RADAR_DOMINIO "Dominio de Radar [$(_o_default RADAR_DOMINIO radar.keepitsimple.com.ar)]:"
RADAR_DOMINIO=${RADAR_DOMINIO:-radar.keepitsimple.com.ar}
write_env RADAR_DOMINIO "$RADAR_DOMINIO"
if confirm "¿Agrego $RADAR_DOMINIO al servicio $RADAR_SVC?"; then
  railway domain "$RADAR_DOMINIO" --service "$RADAR_SVC" --port 8000 || warn "Si ya estaba agregado, seguí."
fi
step "En tu proveedor de DNS, cargá el registro que muestra Railway (un CNAME, y a veces un TXT de verificación)."
note "Railway emite el certificado solo cuando el DNS resuelve; puede tardar desde minutos hasta horas."
pause "Enter cuando lo hayas cargado"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Correo saliente (SMTP)"
say "Radar manda por email los links para entrar y las invitaciones a los dueños."
RADAR_MAILER=smtp
if confirm "¿Los mandás desde una cuenta de Google Workspace?"; then
  SMTP_HOST=smtp.gmail.com; SMTP_PORT=587; SMTP_SEGURIDAD=starttls
  step "La cuenta necesita la verificación en dos pasos activa."
  open_url "https://myaccount.google.com/apppasswords"
  step "Creá una contraseña de aplicación llamada «Radar» y copiá los 16 caracteres."
  ask SMTP_USUARIO "Email de esa cuenta:"
  ask_secret SMTP_PASSWORD "Contraseña de aplicación (no se muestra):"
  ask RADAR_REMITENTE "Remitente (Enter = la misma cuenta; otra dirección tiene que ser un alias suyo):"
  if [[ -z "$RADAR_REMITENTE" ]]; then RADAR_REMITENTE=$SMTP_USUARIO; fi
else
  ask SMTP_HOST "Host SMTP:"
  ask SMTP_PORT "Puerto [587]:"
  SMTP_PORT=${SMTP_PORT:-587}
  ask SMTP_SEGURIDAD "Seguridad: starttls o ssl [starttls]:"
  SMTP_SEGURIDAD=${SMTP_SEGURIDAD:-starttls}
  ask SMTP_USUARIO "Usuario SMTP:"
  ask_secret SMTP_PASSWORD "Contraseña SMTP (no se muestra):"
  ask RADAR_REMITENTE "Remitente (una dirección verificada en ese proveedor):"
fi
write_env SMTP_HOST "$SMTP_HOST"
write_env SMTP_PORT "$SMTP_PORT"
write_env SMTP_SEGURIDAD "$SMTP_SEGURIDAD"
write_env SMTP_USUARIO "$SMTP_USUARIO"
write_env SMTP_PASSWORD "$SMTP_PASSWORD"
write_env RADAR_REMITENTE "$RADAR_REMITENTE"
pause "Enter para seguir"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Claves y variables de Radar"
_secreto RADAR_COOKIE_SECRET 48
_secreto RADAR_WAHA_WEBHOOK_HMAC_KEY 48
_secreto RADAR_APP_DB_PASSWORD 32
ask RADAR_ADMINS_INICIALES "Emails de los admins de KIS, separados por coma:"
write_env RADAR_ADMINS_INICIALES "$RADAR_ADMINS_INICIALES"
R=$RESULTADOS_SVC
F=$FUENTE_SVC
variables=(
  "APP_MODE=radar"
  "PORT=8000"
  "UVICORN_HOST=::"
  "RADAR_BOOTSTRAP_ROLES=true"
  "RADAR_MIGRATOR_DATABASE_URL=\${{${R}.DATABASE_URL}}"
  "RADAR_DATABASE_URL=postgresql://radar_app:${RADAR_APP_DB_PASSWORD}@\${{${R}.PGHOST}}:\${{${R}.PGPORT}}/\${{${R}.PGDATABASE}}"
  "RADAR_FUENTE_DATABASE_URL=\${{${F}.DATABASE_URL}}"
  "RADAR_SECRETS_DIR=/data/radar-secrets"
  "RADAR_COOKIE_SECRET=${RADAR_COOKIE_SECRET}"
  "RADAR_COOKIE_SECURE=true"
  "RADAR_PUBLIC_BASE_URL=https://${RADAR_DOMINIO}"
  "RADAR_ADMINS_INICIALES=${RADAR_ADMINS_INICIALES}"
  "RADAR_MAILER=${RADAR_MAILER}"
  "RADAR_SMTP_HOST=${SMTP_HOST}"
  "RADAR_SMTP_PORT=${SMTP_PORT}"
  "RADAR_SMTP_SEGURIDAD=${SMTP_SEGURIDAD}"
  "RADAR_SMTP_USUARIO=${SMTP_USUARIO}"
  "RADAR_SMTP_PASSWORD=${SMTP_PASSWORD}"
  "RADAR_REMITENTE=${RADAR_REMITENTE}"
  "RADAR_WAHA_WEBHOOK_URL=http://\${{${RADAR_SVC}.RAILWAY_PRIVATE_DOMAIN}}:8000/webhook/waha"
  "RADAR_WAHA_WEBHOOK_HMAC_KEY=${RADAR_WAHA_WEBHOOK_HMAC_KEY}"
)
say "Se van a cargar en el servicio $RADAR_SVC (los secretos no se muestran):"
for v in "${variables[@]}"; do
  clave=${v%%=*}
  if [[ -z "${v#*=}" ]]; then continue; fi
  case "$clave" in
    *PASSWORD*|*SECRET*|*HMAC*) note "  $clave=••••••" ;;
    RADAR_DATABASE_URL) note "  $clave=postgresql://radar_app:••••••@\${{${R}.PGHOST}}:…" ;;
    *) note "  $v" ;;
  esac
done
note "UVICORN_HOST=:: hace que Radar escuche también en IPv6: WAHA le avisa por la red privada."
note "Cargarlas dispara un deploy de $RADAR_SVC."
if confirm "¿Las cargo?"; then
  args=()
  for v in "${variables[@]}"; do
    if [[ -n "${v#*=}" ]]; then args+=(--set "$v"); fi
  done
  if railway variables --service "$RADAR_SVC" "${args[@]}" >/dev/null; then
    say "✓ Variables cargadas."
  else
    warn "railway variables falló. Revisá el nombre del servicio y volvé a correr el asistente."
    exit 1
  fi
else
  SKIPPED+=("cargar las variables de $RADAR_SVC (paso 9)")
fi
pause "Enter para seguir"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Desplegar y esperar que arranque"
say "El primer deploy tarda unos minutos: build, roles de Postgres y migraciones. Y el certificado del dominio, lo que diga el DNS."
cuerpo=$(mktemp)
listo=0
for _ in $(seq 1 90); do
  codigo=$(curl -s -o "$cuerpo" -w '%{http_code}' "https://$RADAR_DOMINIO/health" || true)
  if [[ "$codigo" == "200" ]] && grep -q '"modo":"radar"' "$cuerpo" && grep -q '"status":"ok"' "$cuerpo"; then
    listo=1
    break
  fi
  printf '  %s… todavía no (HTTP %s)%s\r' "$DIM" "${codigo:-—}" "$RESET"
  sleep 10
done
printf '\n'
rm -f "$cuerpo"
if (( listo )); then
  say "✓ Radar está arriba: https://$RADAR_DOMINIO/health responde ok."
else
  warn "No respondió ok en 15 minutos."
  step "Si el DNS todavía no resuelve, es eso: esperá y re-corré el asistente (retoma solo)."
  step "Si no, mirá los logs: railway logs --service $RADAR_SVC --deployment"
  SKIPPED+=("Radar no llegó a /health ok: revisar DNS o logs")
fi
step "En los logs del deploy buscá «RADAR_BOOTSTRAP_ROLES» y «RADAR_ADMINS_INICIALES»: confirman roles y admins."
pause "Enter para seguir"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Entrar a Radar"
open_url "https://$RADAR_DOMINIO/radar/login"
step "Poné tu email (uno de los admins iniciales) y tocá «Recibir el link»."
step "Abrí el link del mail y tocá «Entrar a Radar». Te lleva a la Consola."
note "Si el mail no llega: mirá spam, y en los logs buscá «link no enviado»."
if ! confirm "¿Entraste a la Consola?"; then
  ask ADMIN_EMAIL "Tu email de admin:"
  if confirm "¿Genero un link de invitación con railway ssh? (se muestra solo en esta terminal)"; then
    railway ssh --service "$RADAR_SVC" -- sh -c "cd /app && python scripts/radar_admin.py crear-admin --email '$ADMIN_EMAIL'" \
      || warn "railway ssh falló."
    step "Abrí ese link en el navegador. No lo pegues en ningún chat."
  fi
fi
pause "Enter cuando estés en la Consola"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Cargar el WAHA de producción en la Consola"
waha_privado=$(railway variables --service "$WAHA_SVC" --kv 2>/dev/null | grep '^RAILWAY_PRIVATE_DOMAIN=' | cut -d= -f2- || true)
if [[ -z "$waha_privado" ]]; then
  waha_privado="$WAHA_SVC.railway.internal"
  note "No pude leer el dominio privado de $WAHA_SVC: uso $waha_privado."
fi
open_url "https://$RADAR_DOMINIO/radar/consola"
step "Consola → «Servidores WAHA» → Registrar un servidor:"
say "      Nombre: waha-prod-1 · URL: http://$waha_privado:3000 · Motor: GOWS"
say "      Máximo de sesiones: 50 · Disco total: el del volumen de $WAHA_SVC, en GB"
if confirm "¿Muestro la clave admin para pegarla en el formulario?"; then
  say "      Clave: $WAHA_ADMIN_KEY"
  note "Copiala, pegala y limpiá la pantalla. No la pegues en ningún chat."
fi
step "Tiene que aparecer en la tabla con «Clave cargada: sí»."
note "«No se pudo conectar» = puerto o red privada: avisá antes de seguir. «WAHA rechazó la clave» = la clave."
pause "Enter cuando el servidor aparezca en la tabla"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Validar con la línea de prueba"
warn "Usá SOLO la línea de prueba. Ningún cliente hasta tener la ingesta (tramo 3) y lo legal resuelto."
step "Consola → «Alta»: cliente «KIS prueba», rubro «otros», línea «Línea de prueba», dueño un email tuyo distinto del de admin."
step "En el panel de la línea: consentimiento y «Generar QR»."
step "Chequeo crítico: el webhook de WAHA tiene que entrar con 200 por la red privada."
if confirm "¿Busco «POST /webhook/waha» en los logs ahora (20 segundos)?"; then
  timeout 20 railway logs --service "$RADAR_SVC" 2>/dev/null | grep -E "POST /webhook/waha" | tail -n 5 || true
fi
warn "Si ves 401: no escanees y avisá (formato del HMAC). Si no aparece nada: WAHA no llega a Radar por la red privada."
step "Con 200: escaneá con la línea de prueba y seguí docs/radar-waha-runbook-tramo2.md, secciones 2 a 8."
step "Al terminar: «Desconectar y borrar todo» en la línea de prueba."
pause "Enter para terminar"

finish
note "Valores guardados en $ENV_FILE (incluye la clave admin de WAHA: copiala a tu gestor de contraseñas)."
