#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Radar en Railway (staging). Se corre desde la raíz del worktree de Radar, en
# Git Bash, con la CLI de Railway logueada:
#
#   bash scripts/radar_staging_railway.sh
#
# Guarda lo que generás o pegás en ~/.radar-staging.env (permisos 600, fuera
# del repo), así un re-run retoma donde quedó y no regenera las claves.

TOTAL_STAGES=13
umask 077
ENV_FILE="${RADAR_WIZARD_ENV:-$HOME/.radar-staging.env}"
REPO_SLUG="maoscherov/WhatsappBoty"
RAMA="feature/radar-tramo2"

# Valor guardado, o el default si no hay ninguno.
_o_default() { local v; v=$(_existing "$1" || true); printf '%s' "${v:-$2}"; }

# Genera un secreto aleatorio una sola vez; en re-runs reusa el guardado.
_secreto() {
  local key="$1" largo="$2" valor
  valor=$(_existing "$key" || true)
  if [[ -z "$valor" ]]; then
    valor=$(python -c "import secrets; print(secrets.token_urlsafe($largo))")
    write_env "$key" "$valor"
  else
    printf '  %s✓ ya estaba%s %s\n' "$GREEN" "$RESET" "$key"
  fi
  printf -v "$key" '%s' "$valor"
}

banner "Radar en Railway (staging)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Antes de empezar"
say "Este asistente despliega Radar en Railway desde la rama $RAMA."
say "Lo que generes o pegues queda en $ENV_FILE (solo lo puede leer tu usuario)."
if [[ ! -f app/radar/app.py || ! -f railway.json ]]; then
  warn "Corrélo desde la raíz del worktree de Radar (D:\\Dev\\WhatsappBOTy-radar-tramo2)."
  exit 1
fi
rama_actual=$(git rev-parse --abbrev-ref HEAD)
if [[ "$rama_actual" != "$RAMA" ]]; then
  warn "Estás en la rama $rama_actual; pasate a $RAMA y volvé a correrlo."
  exit 1
fi
if [[ -n "$(git status --porcelain)" ]]; then
  warn "Hay cambios sin commitear. Railway despliega lo que está en GitHub, no esta carpeta."
fi
for cmd in railway curl python git; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    warn "Falta $cmd en el PATH."
    exit 1
  fi
done
if ! railway whoami >/dev/null 2>&1; then
  step "Iniciá sesión en Railway (se abre el navegador):"
  railway login
fi
say "✓ Todo en orden."
pause "Enter para seguir"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Subir la rama a GitHub"
sha_local=$(git rev-parse HEAD)
sha_remoto=$(git ls-remote origin "refs/heads/$RAMA" 2>/dev/null | cut -f1 || true)
if [[ "$sha_remoto" == "$sha_local" ]]; then
  say "✓ GitHub ya tiene $RAMA en ${sha_local:0:7}."
else
  say "Railway despliega desde GitHub: la rama tiene que estar en origin."
  note "Se sube solo $RAMA. No se toca develop ni master, y no se abre ningún PR."
  if confirm "¿Subo $RAMA (${sha_local:0:7}) a origin?"; then
    git push -u origin "$RAMA"
  else
    SKIPPED+=("git push -u origin $RAMA")
    warn "Sin la rama en GitHub, Railway no la puede desplegar."
  fi
fi
pause "Enter para seguir"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Elegir el proyecto de Railway"
say "Usá el mismo proyecto donde está el WAHA GOWS de staging."
step "Elegí el proyecto y el entorno con las flechas y Enter."
note "Si la terminal no muestra el menú, corré «railway link» en PowerShell en esta misma carpeta y volvé."
railway link || warn "railway link no terminó bien; si ya vinculaste la carpeta, seguí."
railway status || true
pause "Enter para seguir"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Las dos bases de Postgres"
say "Radar usa dos Postgres propios: resultados y fuente. Nunca la base del bot."
railway open >/dev/null 2>&1 || warn "No se pudo abrir el proyecto: abrilo en railway.com."
step "En el proyecto: «+ Create» (o «New») → Database → PostgreSQL. Repetilo: tienen que ser dos."
step "Renombrá cada uno (clic en el servicio → Settings → nombre del servicio):"
say "      RadarResultados   y   RadarFuente"
note "Los nombres importan: las variables de Radar los referencian por nombre."
pause "Enter cuando estén las dos creadas y renombradas"
ask RESULTADOS_SVC "Nombre de la base de resultados [$(_o_default RESULTADOS_SVC RadarResultados)]:"
RESULTADOS_SVC=${RESULTADOS_SVC:-RadarResultados}
ask FUENTE_SVC "Nombre de la base de fuente [$(_o_default FUENTE_SVC RadarFuente)]:"
FUENTE_SVC=${FUENTE_SVC:-RadarFuente}
for svc in "$RESULTADOS_SVC" "$FUENTE_SVC"; do
  if railway variables --service "$svc" --kv >/dev/null 2>&1; then
    say "✓ Encontré $svc."
  else
    warn "No encontré el servicio $svc en el proyecto vinculado. Revisá el nombre antes de seguir."
  fi
done
write_env RESULTADOS_SVC "$RESULTADOS_SVC"
write_env FUENTE_SVC "$FUENTE_SVC"
pause "Enter para seguir"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "El servicio de Radar"
step "En el mismo proyecto: «+ Create» → GitHub Repo → $REPO_SLUG."
step "Renombralo a «radar» (Settings → nombre del servicio)."
step "Settings → Source → Branch: elegí $RAMA."
note "Si arranca un deploy antes de que cargues las variables y falla, es normal."
note "No le generes dominio a mano: lo hace el paso 7."
pause "Enter cuando el servicio exista y apunte a $RAMA"
ask RADAR_SVC "Nombre del servicio de Radar [$(_o_default RADAR_SVC radar)]:"
RADAR_SVC=${RADAR_SVC:-radar}
write_env RADAR_SVC "$RADAR_SVC"
railway service "$RADAR_SVC" || warn "No pude vincular el servicio $RADAR_SVC; revisá el nombre."
pause "Enter para seguir"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Volumen para los secretos"
say "Las claves de los clientes y la clave admin de WAHA viven en un volumen, fuera de Postgres."
volumenes=$(railway volume list 2>/dev/null || true)
if grep -q "/data" <<<"$volumenes"; then
  say "✓ Ya hay un volumen montado en /data."
elif confirm "¿Creo un volumen montado en /data para $RADAR_SVC?"; then
  railway volume add --mount-path /data
  railway volume list || true
else
  step "Hacelo a mano: clic derecho en el servicio → Attach volume → mount path /data."
  pause "Enter cuando esté"
fi
note "Si activás backups de este volumen, tené en cuenta que guardan esas claves."
pause "Enter para seguir"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Dominio público"
RADAR_DOMINIO=$(_existing RADAR_DOMINIO || true)
if [[ -n "$RADAR_DOMINIO" ]]; then
  say "✓ Dominio guardado: $RADAR_DOMINIO"
else
  salida=$(railway domain --service "$RADAR_SVC" --port 8000 2>&1 || true)
  RADAR_DOMINIO=$(printf '%s' "$salida" | grep -oE '[a-z0-9.-]+\.up\.railway\.app' | head -n1 || true)
  if [[ -z "$RADAR_DOMINIO" ]]; then
    step "Settings → Networking → Generate Domain, con el puerto 8000."
    ask RADAR_DOMINIO "Pegá el dominio (sin https://):"
  fi
  write_env RADAR_DOMINIO "$RADAR_DOMINIO"
fi
say "Radar va a quedar en https://$RADAR_DOMINIO"
pause "Enter para seguir"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Correo saliente (SMTP)"
say "Radar manda por email los links para entrar y las invitaciones a los dueños."
RADAR_MAILER=smtp
if confirm "¿Los mandás desde una cuenta de Google Workspace?"; then
  SMTP_HOST=smtp.gmail.com; SMTP_PORT=587; SMTP_SEGURIDAD=starttls
  step "La cuenta necesita la verificación en dos pasos activa."
  open_url "https://myaccount.google.com/apppasswords"
  step "Creá una contraseña de aplicación llamada «Radar» y copiá los 16 caracteres."
  note "Si la página dice que no está disponible: falta la verificación en dos pasos, o el admin de Workspace bloqueó las contraseñas de aplicación."
  ask SMTP_USUARIO "Email de esa cuenta:"
  ask_secret SMTP_PASSWORD "Contraseña de aplicación (no se muestra):"
  ask RADAR_REMITENTE "Remitente (Enter = la misma cuenta; otra dirección tiene que ser un alias suyo):"
  if [[ -z "$RADAR_REMITENTE" ]]; then RADAR_REMITENTE=$SMTP_USUARIO; fi
elif confirm "¿Tenés otro servidor SMTP (Resend, Brevo, SES…)?"; then
  ask SMTP_HOST "Host SMTP:"
  ask SMTP_PORT "Puerto [587]:"
  SMTP_PORT=${SMTP_PORT:-587}
  ask SMTP_SEGURIDAD "Seguridad: starttls, ssl o ninguna [starttls]:"
  SMTP_SEGURIDAD=${SMTP_SEGURIDAD:-starttls}
  ask SMTP_USUARIO "Usuario SMTP:"
  ask_secret SMTP_PASSWORD "Contraseña SMTP (no se muestra):"
  ask RADAR_REMITENTE "Remitente (una dirección verificada en ese proveedor):"
  if [[ "$SMTP_SEGURIDAD" == "ninguna" && -n "$SMTP_USUARIO" ]]; then
    warn "Radar no manda usuario y contraseña sin cifrar: uso starttls."
    SMTP_SEGURIDAD=starttls
  fi
else
  RADAR_MAILER=log
  SMTP_HOST=""; SMTP_PORT=587; SMTP_SEGURIDAD=starttls; SMTP_USUARIO=""; SMTP_PASSWORD=""; RADAR_REMITENTE=""
  warn "Sin SMTP no sale ningún email. Para entrar vas a generar el link con «railway ssh» (paso 11)."
fi
write_env RADAR_MAILER "$RADAR_MAILER"
write_env SMTP_HOST "$SMTP_HOST"
write_env SMTP_PORT "$SMTP_PORT"
write_env SMTP_SEGURIDAD "$SMTP_SEGURIDAD"
write_env SMTP_USUARIO "$SMTP_USUARIO"
write_env SMTP_PASSWORD "$SMTP_PASSWORD"
write_env RADAR_REMITENTE "$RADAR_REMITENTE"
pause "Enter para seguir"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Claves y variables de Radar"
_secreto RADAR_COOKIE_SECRET 48
_secreto RADAR_WAHA_WEBHOOK_HMAC_KEY 48
_secreto RADAR_APP_DB_PASSWORD 32
ask RADAR_ADMINS_INICIALES "Emails de los admins de KIS, separados por coma:"
write_env RADAR_ADMINS_INICIALES "$RADAR_ADMINS_INICIALES"
R=$RESULTADOS_SVC
F=$FUENTE_SVC
variables=(
  "APP_MODE=radar"
  "PORT=8000"
  "RADAR_BOOTSTRAP_ROLES=true"
  "RADAR_MIGRATOR_DATABASE_URL=\${{${R}.DATABASE_URL}}"
  "RADAR_DATABASE_URL=postgresql://radar_app:${RADAR_APP_DB_PASSWORD}@\${{${R}.PGHOST}}:\${{${R}.PGPORT}}/\${{${R}.PGDATABASE}}"
  "RADAR_FUENTE_DATABASE_URL=\${{${F}.DATABASE_URL}}"
  "RADAR_SECRETS_DIR=/data/radar-secrets"
  "RADAR_COOKIE_SECRET=${RADAR_COOKIE_SECRET}"
  "RADAR_COOKIE_SECURE=true"
  "RADAR_PUBLIC_BASE_URL=https://${RADAR_DOMINIO}"
  "RADAR_ADMINS_INICIALES=${RADAR_ADMINS_INICIALES}"
  "RADAR_MAILER=${RADAR_MAILER}"
  "RADAR_SMTP_HOST=${SMTP_HOST}"
  "RADAR_SMTP_PORT=${SMTP_PORT}"
  "RADAR_SMTP_SEGURIDAD=${SMTP_SEGURIDAD}"
  "RADAR_SMTP_USUARIO=${SMTP_USUARIO}"
  "RADAR_SMTP_PASSWORD=${SMTP_PASSWORD}"
  "RADAR_REMITENTE=${RADAR_REMITENTE}"
  "RADAR_WAHA_WEBHOOK_URL=https://${RADAR_DOMINIO}/webhook/waha"
  "RADAR_WAHA_WEBHOOK_HMAC_KEY=${RADAR_WAHA_WEBHOOK_HMAC_KEY}"
)
say "Se van a cargar en el servicio $RADAR_SVC (los secretos no se muestran):"
for v in "${variables[@]}"; do
  clave=${v%%=*}
  if [[ -z "${v#*=}" ]]; then continue; fi
  case "$clave" in
    *PASSWORD*|*SECRET*|*HMAC*) note "  $clave=••••••" ;;
    RADAR_DATABASE_URL) note "  $clave=postgresql://radar_app:••••••@\${{${R}.PGHOST}}:…" ;;
    *) note "  $v" ;;
  esac
done
note "Cargarlas dispara un deploy de $RADAR_SVC."
if confirm "¿Las cargo?"; then
  args=()
  for v in "${variables[@]}"; do
    if [[ -n "${v#*=}" ]]; then args+=(--set "$v"); fi
  done
  if railway variables --service "$RADAR_SVC" "${args[@]}" >/dev/null; then
    say "✓ Variables cargadas."
  else
    warn "railway variables falló. Revisá el nombre del servicio y volvé a correr el asistente."
    exit 1
  fi
else
  SKIPPED+=("cargar las variables de $RADAR_SVC (paso 9)")
fi
pause "Enter para seguir"

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Desplegar y esperar que arranque"
say "El primer deploy tarda unos minutos: build de la imagen, roles de Postgres y migraciones."
note "Si el deploy no arrancó solo, en el servicio: Deployments → Deploy."
cuerpo=$(mktemp)
listo=0
for _ in $(seq 1 60); do
  codigo=$(curl -s -o "$cuerpo" -w '%{http_code}' "https://$RADAR_DOMINIO/health" || true)
  if [[ "$codigo" == "200" ]] && grep -q '"modo":"radar"' "$cuerpo" && grep -q '"status":"ok"' "$cuerpo"; then
    listo=1
    break
  fi
  printf '  %s… todavía no (HTTP %s)%s\r' "$DIM" "${codigo:-—}" "$RESET"
  sleep 10
done
printf '\n'
rm -f "$cuerpo"
if (( listo )); then
  say "✓ Radar está arriba: https://$RADAR_DOMINIO/health responde ok."
else
  warn "Radar no respondió ok en 10 minutos."
  step "Mirá los logs del deploy: railway logs --service $RADAR_SVC --deployment"
  note "Errores típicos: un nombre de base mal escrito en las referencias, o el volumen sin montar."
  SKIPPED+=("Radar no llegó a /health ok: revisar logs")
fi
pause "Enter para seguir"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Entrar a Radar"
plan_b=1
if [[ "$RADAR_MAILER" == "smtp" ]]; then
  plan_b=0
  open_url "https://$RADAR_DOMINIO/radar/login"
  step "Poné tu email (uno de los admins iniciales) y tocá Entrar."
  step "Abrí el link del mail y, en la página, tocá «Entrar a Radar». Te lleva a la Consola."
  note "Si el mail no llega en 2 minutos: mirá spam, y en los logs buscá «link no enviado»."
  if ! confirm "¿Entraste a la Consola?"; then
    warn "Plan B: generar el link en el servidor con railway ssh."
    plan_b=1
  fi
fi
if (( plan_b )); then
  ask ADMIN_EMAIL "Tu email de admin:"
  if confirm "¿Genero un link de invitación con railway ssh? (se muestra solo en esta terminal)"; then
    railway ssh --service "$RADAR_SVC" -- sh -c "cd /app && python scripts/radar_admin.py crear-admin --email '$ADMIN_EMAIL'" \
      || warn "railway ssh falló: probá desde PowerShell con el mismo comando."
    step "Abrí ese link en el navegador y tocá «Entrar a Radar». No lo pegues en ningún chat."
  fi
fi
pause "Enter cuando estés en la Consola"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Cargar el servidor WAHA"
ask WAHA_URL "URL del WAHA GOWS de staging (https://…):"
write_env WAHA_URL "$WAHA_URL"
open_url "https://$RADAR_DOMINIO/radar/consola"
step "En la Consola, sección «Servidores WAHA», cargá:"
say "      Nombre: gows-staging · URL: $WAHA_URL · Motor: GOWS · Sesiones: 5 · Disco: 5"
say "      Clave admin: la clave EN CLARO de tu gestor de contraseñas (no el hash sha512)."
step "Guardar. Tiene que aparecer en la tabla con «clave cargada: sí»."
note "«WAHA rechazó la clave» = la clave; «no se pudo conectar» = la URL; «otro motor» = el servidor no es GOWS."
pause "Enter cuando el servidor aparezca en la tabla"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Cliente de prueba y QR"
step "Consola → «Alta»: cliente «Prueba», rubro «otros», línea «Línea de prueba»."
step "Dueño: un email tuyo distinto del de admin (sirve tu+dueno@tudominio)."
step "Se abre el panel de la línea: registrá el consentimiento y tocá «Generar QR»."
say ""
step "Chequeo crítico: el webhook de WAHA tiene que entrar con 200."
if confirm "¿Busco «POST /webhook/waha» en los logs ahora (20 segundos)?"; then
  timeout 20 railway logs --service "$RADAR_SVC" 2>/dev/null | grep -E "POST /webhook/waha" | tail -n 5 || true
fi
warn "Si ves 401 en lugar de 200: no escanees y avisá (el formato del HMAC de WAHA no coincide)."
step "Con 200: escaneá el QR con la LÍNEA DE PRUEBA (nunca tu línea personal) y seguí"
say "      docs/radar-waha-runbook-tramo2.md, secciones 2 a 8."
pause "Enter para terminar"

finish
note "Valores guardados en $ENV_FILE (para re-correr el asistente sin regenerar claves)."
note "Para cambiar algo: editá la variable en Railway, o borrá la línea de ese archivo y re-corré."
